In [119]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [120]:
import pandas as pd
import numpy as np

In [121]:
df = pd.read_csv('/content/drive/MyDrive/Dataset/hospital_data_unclean.csv')

In [122]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,M,B-,CANCER,2024.01.31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02/02/2024,Paracetamol,N
1,LEsliE tErrY,62.0,M,A+,OBESITY,2019.08.20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,dAnnY SMiTH,76.0,FEMALE,A-,OBESITY,09/22/2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11/18/2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020.12.18,Ibuprofen,abn
4,ADRIeNNe bELL,43.0,FEMALE,AB+-,CANCER,2022.09.19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10/09/2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,cASsanDRA cArNEy,32.0,M,B+,HYPERTENSION,02/21/2022,Cassandra Montoya ##,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. dAViD SmITh,18.0,M,A+,HYPERTENSION,23-10-2019,Eric Martinez ##,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,liSA aLlen,65.0,M,O--,OBESITY,20-12-2019,Daryl Mckinney ##,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020.01.05,Aspirin,abn
55503,AAron craig,22.0,FEMALE,O-+,ARTHRITIS,2024.03.21,Justin Wolfe ##,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04/19/2024,Ibuprofen,unknown
55504,aShlEy MACdoNAlD,36.0,FEMALE,B+,HYPERTENSION,07/18/2019,Roy Perkins ##,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,NaN,Penicillin,N

In [123]:
df.isna().sum()

Name                  4440
Age                   4440
Gender                4440
Blood Type            4440
Medical Condition     4440
Date of Admission     4440
Doctor                4440
Hospital              4441
Insurance Provider    4442
Billing Amount        4440
Room Number           4441
Admission Type        4440
Discharge Date        4441
Medication            4440
Test Results          4440
dtype: int64

In [124]:
df.shape

(55505, 15)

In [125]:
# Name column correction to standard title
df['Name'] = df['Name'].str.title()
df['Name']

0                     NaN
1            Leslie Terry
2             Danny Smith
3                     NaN
4           Adrienne Bell
               ...
55500    Cassandra Carney
55501     Dr. David Smith
55502          Lisa Allen
55503         Aaron Craig
55504    Ashley Macdonald
Name: Name, Length: 55505, dtype: object

In [126]:
df['Gender'] = df['Gender'].replace({"M":"MALE", "F":"FEMALE"})
df['Gender']

0          MALE
1          MALE
2        FEMALE
3        FEMALE
4        FEMALE
          ...
55500      MALE
55501      MALE
55502      MALE
55503    FEMALE
55504    FEMALE
Name: Gender, Length: 55505, dtype: object

In [127]:
# You can check the data types of all columns in your DataFrame using df.dtypes.
df.dtypes

Name                   object
Age                   float64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount         object
Room Number           float64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [128]:
df['Date of Admission'] = df['Date of Admission'].astype(str)
df['Discharge Date'] = df['Discharge Date'].astype(str)

In [129]:
df.dtypes

Name                   object
Age                   float64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount         object
Room Number           float64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [130]:
df['Date of Admission'] = df['Date of Admission'].str.replace('.', '-', regex=False)
df['Discharge Date'] = df['Discharge Date'].str.replace('.', '-', regex=False)
df['Date of Admission'] = df['Date of Admission'].str.replace('/', '-', regex=False)
df['Discharge Date'] = df['Discharge Date'].str.replace('/', '-', regex=False)

In [131]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,MALE,B-,CANCER,2024-01-31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,MALE,A+,OBESITY,2019-08-20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022-09-19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,MALE,B+,HYPERTENSION,02-21-2022,Cassandra Montoya ##,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,MALE,A+,HYPERTENSION,23-10-2019,Eric Martinez ##,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,MALE,O--,OBESITY,20-12-2019,Daryl Mckinney ##,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024-03-21,Justin Wolfe ##,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins ##,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [132]:
# replace the '#' character with a space in the 'Doctor' column

df['Doctor'] = df['Doctor'].str.replace('#', ' ', regex=False)
df['Doctor'].head()

0      Matthew Smith
1    Samantha Davies
2                   NaN
3        Kevin Wells
4     Kathleen Hanna
Name: Doctor, dtype: object

In [133]:
# replace the commas with spaces in the Hospital column for you.

df['Hospital'] = df['Hospital'].str.replace(",","")
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,MALE,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,MALE,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,MALE,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,MALE,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,MALE,O--,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [134]:
df['Hospital'] = df['Hospital'].fillna('unknown')
df.isna().sum()

Name                  4440
Age                   4440
Gender                4440
Blood Type            4440
Medical Condition     4440
Date of Admission        0
Doctor                4440
Hospital                 0
Insurance Provider    4442
Billing Amount        4440
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication            4440
Test Results          4440
dtype: int64

In [135]:
df.isna().sum()

Name                  4440
Age                   4440
Gender                4440
Blood Type            4440
Medical Condition     4440
Date of Admission        0
Doctor                4440
Hospital                 0
Insurance Provider    4442
Billing Amount        4440
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication            4440
Test Results          4440
dtype: int64

In [136]:
# Here are the unique items in the 'Insurance Provider' column:

df['Insurance Provider'].unique()

array(['Blue Cross', 'Medicare', 'Aetna', nan, 'UnitedHealthcare',
       'Cigna'], dtype=object)

In [137]:
#  All instances of 'UnitedHealthcare' should now appear as 'United Healthcare'.

df['Insurance Provider'] = df['Insurance Provider'].str.replace('UnitedHealthcare', 'United Healthcare', regex=False)

In [138]:
# fill the null values in the 'Name' column with 'unknown'.

df['Name'] = df['Name'].fillna('unknown')
df['Name'].head()

0          unknown
1     Leslie Terry
2      Danny Smith
3          unknown
4    Adrienne Bell
Name: Name, dtype: object

In [139]:
df['Age'].dtype

dtype('float64')

In [140]:
# Calculate the mean of the 'Age' column
age_mean = df['Age'].mean()

# Fill null values in 'Age' column with the calculated mean
df['Age'] = df['Age'].fillna(age_mean)

# Display the first few rows of the 'Age' column to show the effect
df['Age'].head()

0    30.0
1    62.0
2    76.0
3    28.0
4    43.0
Name: Age, dtype: float64

In [141]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,MALE,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,MALE,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022-09-19,Kathleen Hanna,unknown,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,MALE,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,MALE,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,MALE,O--,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,unknown,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [142]:
df['Gender'].value_counts()

Gender
MALE      25605
FEMALE    25460
Name: count, dtype: int64

In [143]:
# Calculate the mode of the 'Gender' column
gender_mode = df['Gender'].mode()[0]

# Fill null values in 'Gender' column with the calculated mode
df['Gender'] = df['Gender'].fillna(gender_mode)

# Display the value counts of the 'Gender' column to show the effect
df['Gender'].value_counts()

Gender
MALE      30045
FEMALE    25460
Name: count, dtype: int64

In [144]:
# Calculate the mode of the 'Blood Type' column
blood_type_mode = df['Blood Type'].mode()[0]

# Fill null values in 'Blood Type' column with the calculated mode
df['Blood Type'] = df['Blood Type'].fillna(blood_type_mode)

# Display the value counts of the 'Blood Type' column to show the effect
df['Blood Type'].value_counts()

Blood Type
A-      6110
O+      1650
B-      1644
O-      1639
A+      1637
AB-     1627
B-+     1620
AB+-    1619
A+-     1618
AB-+    1618
B+-     1613
AB+     1613
B-      1605
A-      1603
B+      1597
B++     1588
A--     1586
AB++    1582
B+      1582
O++     1579
A+      1576
A++     1572
AB+     1571
A-+     1569
B--     1569
AB-     1567
AB--    1565
O--     1565
O+-     1562
O+      1557
O-+     1556
O-      1546
Name: count, dtype: int64

In [145]:
# Fill null values in 'Doctor' column with the calculated mode
df['Doctor'] = df['Doctor'].fillna("unknown")

# Display the value counts of the 'Doctor' column to show the effect
df['Doctor'].value_counts()

Doctor
unknown                4440
Michael Smith            24
John Smith               21
Michael Johnson          20
Robert Smith             19
                       ...
Brady Burke               1
Laura Robinson            1
Kristen King              1
Nicholas Schmidt          1
Bernard Ruiz              1
Name: count, Length: 37820, dtype: int64

In [146]:
df['Medical Condition'].value_counts()

Medical Condition
ARTHRITIS       8598
DIABETES        8574
HYPERTENSION    8507
OBESITY         8497
ASTHMA          8459
CANCER          8430
Name: count, dtype: int64

In [147]:
df['Medical Condition'] = df['Medical Condition'].fillna('unknown')
df['Medical Condition'].value_counts()

Medical Condition
ARTHRITIS       8598
DIABETES        8574
HYPERTENSION    8507
OBESITY         8497
ASTHMA          8459
CANCER          8430
unknown         4440
Name: count, dtype: int64

In [148]:
df['Insurance Provider'] = df['Insurance Provider'].fillna('unknown')
df['Insurance Provider'].head()

0    Blue Cross
1      Medicare
2         Aetna
3      Medicare
4       unknown
Name: Insurance Provider, dtype: object

In [149]:
df['Billing Amount'] = df['Billing Amount'].astype(str)
df['Billing Amount'] = df['Billing Amount'].str.replace(" USD","")
df['Billing Amount'].head()

0    18856.281305978155
1    33643.327286577885
2    27955.096078842456
3     37909.78240987528
4    14238.317813937623
Name: Billing Amount, dtype: object

In [150]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,MALE,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,MALE,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,unknown,Cook PLC,Aetna,27955.096078842456,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022-09-19,Kathleen Hanna,unknown,unknown,14238.317813937623,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,MALE,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,unknown,19601.381722682367,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,MALE,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,MALE,O--,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,unknown,36639.9788574008,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,unknown,Medicare,13007.88736491442,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194,NaN,Emergency,nan,Penicillin,N

In [151]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission        0
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication            4440
Test Results          4440
dtype: int64

In [152]:
df['Medication'] = df['Medication'].fillna('unknown')
df['Medication'].value_counts()

Medication
Lipitor        10281
Ibuprofen      10245
Aspirin        10205
Paracetamol    10167
Penicillin     10167
unknown         4440
Name: count, dtype: int64

In [153]:
df['Medication'].value_counts()

Medication
Lipitor        10281
Ibuprofen      10245
Aspirin        10205
Paracetamol    10167
Penicillin     10167
unknown         4440
Name: count, dtype: int64

In [154]:
df['Test Results'].value_counts()

Test Results
abn        17123
N          17039
unknown    16903
Name: count, dtype: int64

In [155]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission        0
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication               0
Test Results          4440
dtype: int64

In [156]:
df['Test Results'] = df['Test Results'].fillna('unknown')
df['Test Results'].value_counts()

Test Results
unknown    21343
abn        17123
N          17039
Name: count, dtype: int64

In [157]:
df['Room Number'] = df['Room Number'].fillna('not assigned')
df['Room Number'].head()

0    328.0
1    265.0
2    205.0
3    450.0
4    458.0
Name: Room Number, dtype: object

In [158]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission        0
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number              0
Admission Type        4440
Discharge Date           0
Medication               0
Test Results             0
dtype: int64

In [159]:
df['Admission Type'] = df['Admission Type'].fillna('unknown')
df['Admission Type'].value_counts()

Admission Type
Elective     17189
Urgent       17056
Emergency    16820
unknown       4440
Name: count, dtype: int64

In [160]:
df.isna().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [161]:
df['Date of Admission'] = df['Date of Admission'].astype(str).str.strip()
df['Discharge Date'] = df['Discharge Date'].astype(str).str.strip()
dates = pd.to_datetime(df['Date of Admission'], errors='coerce')

In [162]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,MALE,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,MALE,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,unknown,Cook PLC,Aetna,27955.096078842456,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022-09-19,Kathleen Hanna,unknown,unknown,14238.317813937623,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,MALE,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,unknown,19601.381722682367,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,MALE,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,MALE,O--,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,unknown,36639.9788574008,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,unknown,Medicare,13007.88736491442,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194,not assigned,Emergency,nan,Penicillin,N

In [163]:
mask = dates.isna()
df.loc[mask, 'Date of Admission']

2        09-22-2022
3        11-18-2020
6        11-03-2020
8        01-07-2020
10       19-04-2020
            ...
55499    02-04-2024
55500    02-21-2022
55501    23-10-2019
55502    20-12-2019
55504    07-18-2019
Name: Date of Admission, Length: 38383, dtype: object

In [164]:
# First snippet: Basic string cleaning
df['Blood Type'] = df['Blood Type'].astype(str).str.strip().str.upper()

# Second snippet: Using regex to handle trailing '+' or '-' symbols
df['Blood Type'] = df['Blood Type'].str.replace(r"(\+|-)+$", lambda x: x.group(0)[0].upper(), regex=True)

In [165]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,MALE,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,MALE,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,unknown,Cook PLC,Aetna,27955.096078842456,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,unknown,unknown,14238.317813937623,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,MALE,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,unknown,19601.381722682367,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,MALE,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,MALE,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,unknown,36639.9788574008,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,unknown,Medicare,13007.88736491442,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194,not assigned,Emergency,nan,Penicillin,N

In [166]:
df['Blood Type'].value_counts()

Blood Type
A-     10868
B-      6438
A+      6403
AB+     6385
B+      6380
AB-     6377
O+      6348
O-      6306
Name: count, dtype: int64

In [167]:
import numpy as np

df['Billing Amount'] = df['Billing Amount'].replace('nan', np.nan) # Replace string 'nan' with actual NaN
df['Billing Amount'] = pd.to_numeric(df['Billing Amount'], errors='coerce').round(2)
df['Billing Amount'].head()

0    18856.28
1    33643.33
2    27955.10
3    37909.78
4    14238.32
Name: Billing Amount, dtype: float64

In [168]:
df.to_csv('Hospital_data_cleaned.csv',index=False)

In [169]:
from google.colab import files
files.download('Hospital_data_cleaned.csv')